spring:
  profiles:
    active: dev

---
server:
  port: 4000

spring:
  profiles: dev
  application:
    name: config-dev


---
server:
  port: 4001
spring:
  profiles: online
  application:
    name: config-online